import React, { useEffect, useRef } from 'react';

export default function NagpurCulturalSystem() {
  const canvasRef = useRef(null);
  const scrollPosRef = useRef(0);
  const scrollVelRef = useRef(0);
  const mousePosRef = useRef({ x: -1000, y: -1000, active: false });
  const animFrameRef = useRef(null);

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext('2d');

    let width = (canvas.width = window.innerWidth);
    let height = (canvas.height = window.innerHeight);

    const handleResize = () => {
      width = canvas.width = window.innerWidth;
      height = canvas.height = window.innerHeight;
    };
    window.addEventListener('resize', handleResize);

    // Passive Scroll Listener for Velocity & Morph Progress
    let lastScroll = window.scrollY;
    let burstTimer = 0;

    const handleScroll = () => {
      const currentScroll = window.scrollY;
      const delta = Math.abs(currentScroll - lastScroll);
      scrollVelRef.current = Math.min(scrollVelRef.current + delta * 0.15, 25);
      scrollPosRef.current = currentScroll;
      lastScroll = currentScroll;

      if (delta > 35) {
        burstTimer = 25; // 300-500ms energy burst on rapid scroll
      }
    };
    window.addEventListener('scroll', handleScroll, { passive: true });

    // Mouse Interaction Listener
    const handleMouseMove = (e) => {
      mousePosRef.current = { x: e.clientX, y: e.clientY, active: true };
    };
    const handleMouseLeave = () => {
      mousePosRef.current.active = false;
    };
    window.addEventListener('mousemove', handleMouseMove);
    window.addEventListener('mouseleave', handleMouseLeave);

    // -------------------------------------------------------------------
    // AMBIENT STAR CLUSTERS & DRIFTING PARTICLES
    // -------------------------------------------------------------------
    const ambientStars = Array.from({ length: 60 }, () => ({
      x: Math.random() * width,
      y: Math.random() * height,
      size: Math.random() * 1.8 + 0.6,
      color: Math.random() > 0.5 ? '#FF6D00' : Math.random() > 0.5 ? '#4285F4' : '#34A853',
      alpha: Math.random() * 0.5 + 0.2,
      vx: (Math.random() - 0.5) * 0.3,
      vy: (Math.random() - 0.5) * 0.3
    }));

    // -------------------------------------------------------------------
    // 6 ORBITAL HERITAGE SYSTEMS
    // -------------------------------------------------------------------
    
    // Orbit 2: Orange City Particles (32 particles)
    const orangeParticles = Array.from({ length: 32 }, (_, i) => ({
      angle: (i / 32) * Math.PI * 2,
      speed: 0.003 + Math.random() * 0.002,
      radiusOffset: (Math.random() - 0.5) * 25,
      size: Math.random() * 2.8 + 1.5,
      alpha: Math.random() * 0.6 + 0.4,
      isCluster: Math.random() > 0.7
    }));

    // Orbit 3: Deekshabhoomi Dome Radial Geometry (12 nodes)
    const domeNodes = Array.from({ length: 12 }, (_, i) => ({
      angle: (i / 12) * Math.PI * 2,
      pulseSeed: Math.random() * 10
    }));

    // Orbit 4: Sitabuldi Fort Sentinel Line-Art (8 nodes)
    const fortNodes = Array.from({ length: 8 }, (_, i) => ({
      angle: (i / 8) * Math.PI * 2,
      heightOffset: Math.random() * 18
    }));

    // Orbit 5: Railway Junction Network (18 glowing track nodes)
    const railwayNodes = Array.from({ length: 18 }, (_, i) => ({
      angle: (i / 18) * Math.PI * 2,
      speed: (i % 2 === 0 ? 1 : -1) * (0.006 + Math.random() * 0.004),
      nodeSize: 3 + (i % 3)
    }));

    // Orbit 6: Futala Lake Ripples (3 wave rings)
    const waveRings = [
      { radiusRatio: 0.88, phase: 0 },
      { radiusRatio: 0.94, phase: Math.PI / 3 },
      { radiusRatio: 1.02, phase: (Math.PI * 2) / 3 }
    ];

    // Ripple pools generated by mouse or rapid scroll
    const activeRipples = [];

    let rotationAngle1 = 0;
    let rotationAngle2 = 0;
    let rotationAngle3 = 0;
    let rotationAngle4 = 0;
    let rotationAngle5 = 0;
    let rotationAngle6 = 0;

    let timeSec = 0;

    // -------------------------------------------------------------------
    // RENDER LOOP (60 FPS)
    // -------------------------------------------------------------------
    const render = () => {
      timeSec += 0.016;

      // Scroll Velocity Decay
      scrollVelRef.current *= 0.92;
      const currentVel = scrollVelRef.current;
      const isBurst = burstTimer > 0;
      if (burstTimer > 0) burstTimer--;

      // Heritage to Tech Morph Progress (0 at top, 1 at bottom)
      const maxScroll = Math.max(1, document.documentElement.scrollHeight - height);
      const morphProgress = Math.min(1, Math.max(0, scrollPosRef.current / maxScroll));

      // Color System Lerp
      const primaryAccent = morphProgress < 0.5 ? '#FF6D00' : '#4285F4';
      const secondaryAccent = morphProgress < 0.5 ? '#FBBC04' : '#34A853';

      ctx.clearRect(0, 0, width, height);

      const cx = width / 2;
      const cy = height / 2;

      // -----------------------------------------------------------------
      // AMBIENT DRIFTING STAR PARTICLES & CONSTELLATION LINES
      // -----------------------------------------------------------------
      ambientStars.forEach((star, idx) => {
        star.x += star.vx;
        star.y += star.vy;
        if (star.x < 0) star.x = width;
        if (star.x > width) star.x = 0;
        if (star.y < 0) star.y = height;
        if (star.y > height) star.y = 0;

        ctx.beginPath();
        ctx.arc(star.x, star.y, star.size, 0, Math.PI * 2);
        ctx.fillStyle = star.color;
        ctx.globalAlpha = star.alpha * 0.6;
        ctx.fill();

        // Connect nearby ambient stars
        for (let j = idx + 1; j < ambientStars.length; j += 6) {
          const star2 = ambientStars[j];
          const dist = Math.hypot(star.x - star2.x, star.y - star2.y);
          if (dist < 130) {
            ctx.beginPath();
            ctx.moveTo(star.x, star.y);
            ctx.lineTo(star2.x, star2.y);
            ctx.strokeStyle = primaryAccent;
            ctx.globalAlpha = (1 - dist / 130) * 0.08;
            ctx.lineWidth = 0.5;
            ctx.stroke();
          }
        }
      });

      // Base Orbital Radius (Responsive to screen size)
      const baseRadius = Math.min(width, height) * 0.38;

      // Incremental Rotations (Velocity-sensitive)
      const velMultiplier = 1 + currentVel * 0.12 + (isBurst ? 1.5 : 0);
      rotationAngle1 += 0.001 * velMultiplier;
      rotationAngle2 += 0.003 * velMultiplier;
      rotationAngle3 -= 0.0025 * velMultiplier;
      rotationAngle4 += 0.004 * velMultiplier;
      rotationAngle5 -= 0.006 * velMultiplier;
      rotationAngle6 += 0.0012 * velMultiplier;

      // Mouse Interaction Reaction
      const mouse = mousePosRef.current;
      if (mouse.active && Math.random() < 0.08) {
        activeRipples.push({
          x: mouse.x,
          y: mouse.y,
          r: 5,
          maxR: 80 + Math.random() * 40,
          alpha: 0.6
        });
      }

      // Draw Active Mouse/Scroll Ripples
      for (let i = activeRipples.length - 1; i >= 0; i--) {
        const r = activeRipples[i];
        r.r += 2.5;
        r.alpha -= 0.015;
        if (r.alpha <= 0 || r.r >= r.maxR) {
          activeRipples.splice(i, 1);
          continue;
        }
        ctx.beginPath();
        ctx.arc(r.x, r.y, r.r, 0, Math.PI * 2);
        ctx.strokeStyle = primaryAccent;
        ctx.globalAlpha = r.alpha * 0.5;
        ctx.lineWidth = 1;
        ctx.stroke();
      }

      // =================================================================
      // ORBIT 1: ZERO MILE DATUM (CENTER ORIGIN)
      // =================================================================
      ctx.save();
      ctx.translate(cx, cy);
      ctx.rotate(rotationAngle1);

      // Center Coordinate Crosshair Lines
      ctx.beginPath();
      ctx.moveTo(-40, 0); ctx.lineTo(40, 0);
      ctx.moveTo(0, -40); ctx.lineTo(0, 40);
      ctx.strokeStyle = primaryAccent;
      ctx.globalAlpha = 0.25;
      ctx.lineWidth = 1;
      ctx.setLineDash([4, 4]);
      ctx.stroke();
      ctx.setLineDash([]);

      // Concentric Origin Rings
      const r1 = baseRadius * 0.25;
      ctx.beginPath();
      ctx.arc(0, 0, r1, 0, Math.PI * 2);
      ctx.strokeStyle = primaryAccent;
      ctx.globalAlpha = 0.18;
      ctx.stroke();

      // Zero Mile Datum Center Point
      ctx.beginPath();
      ctx.arc(0, 0, 4, 0, Math.PI * 2);
      ctx.fillStyle = primaryAccent;
      ctx.globalAlpha = 0.8;
      ctx.fill();

      ctx.restore();

      // =================================================================
      // ORBIT 2: ORANGE CITY CITRUS PARTICLES
      // =================================================================
      const r2 = baseRadius * 0.5;
      ctx.save();
      ctx.translate(cx, cy);

      // Draw Orbit 2 Guideline
      ctx.beginPath();
      ctx.arc(0, 0, r2, 0, Math.PI * 2);
      ctx.strokeStyle = '#FF6D00';
      ctx.globalAlpha = 0.08;
      ctx.lineWidth = 1;
      ctx.stroke();

      // Render Orange Particles
      orangeParticles.forEach((p) => {
        p.angle += p.speed * velMultiplier;
        const currentR = r2 + p.radiusOffset + Math.sin(timeSec * 2 + p.angle) * 8;
        const px = Math.cos(p.angle) * currentR;
        const py = Math.sin(p.angle) * currentR;

        ctx.beginPath();
        ctx.arc(px, py, p.size * (isBurst ? 1.6 : 1), 0, Math.PI * 2);
        ctx.fillStyle = '#FF6D00';
        ctx.globalAlpha = p.alpha * (morphProgress > 0.6 ? 0.4 : 0.8);
        ctx.fill();

        // Cluster energy lines
        if (p.isCluster) {
          ctx.beginPath();
          ctx.arc(px, py, p.size * 3, 0, Math.PI * 2);
          ctx.strokeStyle = '#FBBC04';
          ctx.globalAlpha = 0.15;
          ctx.stroke();
        }
      });
      ctx.restore();

      // =================================================================
      // ORBIT 3: DEEKSHABHOOMI DOME RADIAL HARMONY
      // =================================================================
      const r3 = baseRadius * 0.75;
      ctx.save();
      ctx.translate(cx, cy);
      ctx.rotate(rotationAngle3);

      ctx.beginPath();
      ctx.arc(0, 0, r3, 0, Math.PI * 2);
      ctx.strokeStyle = secondaryAccent;
      ctx.globalAlpha = 0.12;
      ctx.setLineDash([6, 6]);
      ctx.stroke();
      ctx.setLineDash([]);

      // Radial Arch Geometry Nodes
      domeNodes.forEach((dn) => {
        const angle = dn.angle;
        const px = Math.cos(angle) * r3;
        const py = Math.sin(angle) * r3;

        // Arch curve towards center
        ctx.beginPath();
        ctx.quadraticCurveTo(0, 0, px, py);
        ctx.strokeStyle = secondaryAccent;
        ctx.globalAlpha = 0.06;
        ctx.lineWidth = 1;
        ctx.stroke();

        // Pulsing Dome Node
        ctx.beginPath();
        ctx.arc(px, py, 3.5, 0, Math.PI * 2);
        ctx.fillStyle = secondaryAccent;
        ctx.globalAlpha = 0.6;
        ctx.fill();
      });
      ctx.restore();

      // =================================================================
      // ORBIT 4: SITABULDI FORT ARCHITECTURAL LINE-ART
      // =================================================================
      const r4 = baseRadius * 1.0;
      ctx.save();
      ctx.translate(cx, cy);
      ctx.rotate(rotationAngle4);

      ctx.beginPath();
      ctx.arc(0, 0, r4, 0, Math.PI * 2);
      ctx.strokeStyle = primaryAccent;
      ctx.globalAlpha = 0.1;
      ctx.lineWidth = 1;
      ctx.stroke();

      fortNodes.forEach((fn) => {
        const px = Math.cos(fn.angle) * r4;
        const py = Math.sin(fn.angle) * r4;

        // Fort Sentinel Line-art Pillar
        const h = fn.heightOffset;
        ctx.beginPath();
        ctx.moveTo(px, py);
        ctx.lineTo(px * (1 + h / r4), py * (1 + h / r4));
        ctx.strokeStyle = primaryAccent;
        ctx.globalAlpha = 0.4;
        ctx.lineWidth = 1.5;
        ctx.stroke();
      });
      ctx.restore();

      // =================================================================
      // ORBIT 5: NAGPUR RAILWAY JUNCTION NETWORK
      // =================================================================
      const r5 = baseRadius * 1.25;
      ctx.save();
      ctx.translate(cx, cy);

      ctx.beginPath();
      ctx.arc(0, 0, r5, 0, Math.PI * 2);
      ctx.strokeStyle = '#4285F4';
      ctx.globalAlpha = 0.15;
      ctx.lineWidth = 1.2;
      ctx.stroke();

      // Render Track Nodes & Interconnection Flash
      railwayNodes.forEach((rn, idx) => {
        rn.angle += rn.speed * velMultiplier;
        const nx = Math.cos(rn.angle) * r5;
        const ny = Math.sin(rn.angle) * r5;

        // Draw track node
        ctx.beginPath();
        ctx.arc(nx, ny, rn.nodeSize * (isBurst ? 1.5 : 1), 0, Math.PI * 2);
        ctx.fillStyle = idx % 2 === 0 ? '#4285F4' : '#EA4335';
        ctx.globalAlpha = 0.7;
        ctx.fill();

        // Connect nearby nodes with railway signal bridge
        for (let j = idx + 1; j < railwayNodes.length; j++) {
          const rn2 = railwayNodes[j];
          const nx2 = Math.cos(rn2.angle) * r5;
          const ny2 = Math.sin(rn2.angle) * r5;
          const dist = Math.hypot(nx - nx2, ny - ny2);

          if (dist < 110) {
            ctx.beginPath();
            ctx.moveTo(nx, ny);
            ctx.lineTo(nx2, ny2);
            ctx.strokeStyle = '#4285F4';
            ctx.globalAlpha = (1 - dist / 110) * 0.35;
            ctx.lineWidth = 1;
            ctx.stroke();
          }
        }
      });
      ctx.restore();

      // =================================================================
      // ORBIT 6: FUTALA LAKE WAVE RIPPLES
      // =================================================================
      const r6 = baseRadius * 1.45;
      ctx.save();
      ctx.translate(cx, cy);
      ctx.rotate(rotationAngle6);

      waveRings.forEach((wr) => {
        const radius = r6 * wr.radiusRatio;
        ctx.beginPath();

        const STEPS = 80;
        for (let s = 0; s <= STEPS; s++) {
          const a = (s / STEPS) * Math.PI * 2;
          const waveOffset = Math.sin(a * 6 + timeSec * 3 + wr.phase) * 6;
          const wrx = Math.cos(a) * (radius + waveOffset);
          const wry = Math.sin(a) * (radius + waveOffset);

          if (s === 0) ctx.moveTo(wrx, wry);
          else ctx.lineTo(wrx, wry);
        }

        ctx.strokeStyle = morphProgress > 0.5 ? '#34A853' : '#4285F4';
        ctx.globalAlpha = 0.09;
        ctx.lineWidth = 1;
        ctx.stroke();
      });
      ctx.restore();

      animFrameRef.current = requestAnimationFrame(render);
    };

    render();

    return () => {
      window.removeEventListener('resize', handleResize);
      window.removeEventListener('scroll', handleScroll);
      window.removeEventListener('mousemove', handleMouseMove);
      window.removeEventListener('mouseleave', handleMouseLeave);
      if (animFrameRef.current) cancelAnimationFrame(animFrameRef.current);
    };
  }, []);

  return (
    <canvas
      ref={canvasRef}
      className="fixed inset-0 pointer-events-none z-0 w-full h-full opacity-90"
      style={{ background: '#0F1115' }}
    />
  );
}
